import React from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white p-8 sm:p-12 shadow-sm rounded-2xl">
        <div className="mb-8">
          <Link href="/" className="inline-flex items-center text-sm font-medium text-blue-600 hover:text-blue-500">
            <ArrowLeft className="w-4 h-4 mr-1" />
            Back to Home
          </Link>
        </div>

        <h1 className="text-3xl font-bold text-gray-900 mb-6">Privacy Policy</h1>
        <p className="text-sm text-gray-500 mb-8">Effective Date: {new Date().toLocaleDateString('en-US')}</p>

        <div className="prose prose-blue max-w-none text-gray-700 space-y-6">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Introduction</h2>
            <p>
              Welcome to <strong>Syllabus to Calendar</strong>. We respect your privacy and are committed to protecting it through our compliance with this policy. This Privacy Policy describes the types of information we may collect from you or that you may provide when you use our application to synchronize course syllabuses with your calendar, and our practices for collecting, using, maintaining, protecting, and disclosing that information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Information We Collect</h2>
            <p className="mb-2">We collect limited information to provide our core scheduling services:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Profile Information:</strong> When you sign in with Google, we collect your basic profile information (Name, Email Address, and Avatar) to identify your account.</li>
              <li><strong>Application Metadata:</strong> PDFs, images, or texts you upload to generate schedules, as well as the structured coursework data extracted by our AI.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">3. How We Use and Protect Google User Data</h2>
            <p className="mb-2">
              Syllabus to Calendar integrates with the Google Calendar API to provide seamless event synchronization. We strictly adhere to the following principles regarding your Google Calendar data:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Specific Access:</strong> We request access only to your Google Calendar. We use this access exclusively to create, read, update, and delete events that are <em>generated by our application</em>. We do not arbitrarily modify or read personal calendar events unrelated to Syllabus to Calendar.</li>
              <li><strong>Strict Data Usage:</strong> Your Google Calendar data is used strictly to sync the course schedules you create within our app to your personal Google Calendar.</li>
              <li><strong>No Data Sharing:</strong> We do not share, transfer, or sell your Google Calendar data to third parties, advertising platforms, or data brokers under any circumstances.</li>
              <li><strong>AI and Machine Learning:</strong> We strongly affirm that <strong>No Google user data</strong> (including calendar events or authentication tokens) is ever used to train generalized AI models.</li>
            </ul>
            <div className="mt-4 p-5 bg-blue-50 border-l-4 border-blue-600 rounded-r-lg">
              <p className="font-semibold text-blue-900 m-0 text-sm tracking-wide uppercase">Google Limited Use Policy Disclosure</p>
              <p className="text-blue-800 text-sm mt-2 leading-relaxed">
                Syllabus to Calendar's use and transfer to any other app of information received from Google APIs will adhere to the <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noopener noreferrer" className="underline font-medium hover:text-blue-900">Google API Services User Data Policy</a>, including the Limited Use requirements.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Data Storage, Security & Retention</h2>
            <p>
              Your OAuth access and refresh tokens are encrypted at rest. We retain your uploaded syllabus data and generated events only for as long as your account is active. We employ industry-standard cloud security infrastructure to prevent unauthorized access.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Data Deletion and Revocation</h2>
            <p>
              You maintain full control over your data. You may revoke Syllabus to Calendar's access to your Google Account at any time via your <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">Google Account Security settings</a>. Furthermore, deleting a course within our app will automatically remove the synced events from your calendar. You may request a complete deletion of your account and all associated data by contacting us directly.
            </p>
          </section>
          
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Contact Information</h2>
            <p>
              If you have any questions, concerns, or requests regarding this Privacy Policy, data privacy practices, or if you wish to exercise your data rights, please contact the lead developer directly at:
            </p>
            <div className="mt-2 bg-gray-50 border border-gray-200 rounded-lg p-4 inline-block shadow-sm">
              <p className="font-medium text-gray-900 mb-1">Privacy & Support Operations</p>
              <a href="mailto:nammount19@gmail.com" className="text-blue-600 hover:text-blue-700 font-medium">nammount19@gmail.com</a>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
