import React from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-white p-8 sm:p-12 shadow-sm rounded-2xl">
        <div className="mb-8">
          <Link href="/" className="inline-flex items-center text-sm font-medium text-blue-600 hover:text-blue-500">
            <ArrowLeft className="w-4 h-4 mr-1" />
            Back to Home
          </Link>
        </div>

        <h1 className="text-3xl font-bold text-gray-900 mb-6">Privacy Policy</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: {new Date().toLocaleDateString('en-US')}</p>

        <div className="prose prose-blue max-w-none text-gray-700 space-y-6">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Introduction</h2>
            <p>
              Welcome to Syllabus to Calendar ("we", "our", or "us"). We are committed to protecting your personal information and your right to privacy. This Privacy Policy governs the privacy policies and practices of our website and mobile application.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Information We Collect</h2>
            <p className="mb-2">We collect personal information that you voluntarily provide to us when you register on the application.</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Personal Information:</strong> Name, email address, profile picture (via Google OAuth).</li>
              <li><strong>Application Data:</strong> Course syllabuses you upload and generated schedules.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">3. How We Use Google Calendar Data</h2>
            <p className="mb-2">
              Our application integrates with the Google Calendar API to provide our core service of syncing your course syllabuses directly to your personal calendar.
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Account Access:</strong> We request access to your Google Calendar only when explicitly authorized by you.</li>
              <li><strong>Data Usage:</strong> We strictly use the calendar API to create, view, update, and delete events that are generated by our application. We do not access calendar events created by you or other applications outside of Syllabus to Calendar context.</li>
              <li><strong>Data Storage:</strong> We securely store Google API access tokens in our database to facilitate background syncing. You may revoke these access tokens at any time from your Google Account settings or within our app.</li>
              <li><strong>Data Sharing:</strong> We <strong>DO NOT</strong> share, transfer, or sell your Google Calendar data to any third-party tools, AI models (for training), or advertising platforms.</li>
            </ul>
            <p className="mt-2 font-medium">
              Our use and transfer to any other app of information received from Google APIs will adhere to the <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">Google API Services User Data Policy</a>, including the Limited Use requirements.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Data Security</h2>
            <p>
              We implement appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Your Data Rights</h2>
            <p>
              You may request to delete your account and all associated data at any time. When you do so, all your Google Calendar API connections, tokens, and uploaded syllabuses will be permanently removed from our servers.
            </p>
          </section>
          
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Contact Us</h2>
            <p>
              If you have questions or comments about this Privacy Policy, please contact the administrator.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
